### PR TITLE
HYCOM initialization fixes for UFS debugging

### PR DESCRIPTION
**Pull request by danrosen25**
Reinitialize arrays to avoid debugging NaN checks and allows for `-check all` during `CMAKE_Fortran_FLAGS_DEBUG`

**Issues Fixed**
Cases where array1(:,:) = array2(:,:) trips a run time NaN check when the active array size (ii,jj) is smaller than the actual array size (idm,jdm).  To avoid this, two arrays are reinitialized to non NaN values.

These changes were completed in collaboration with the NAVY HYCOM team.

### CODE REVIEW

**Comment by BinLiu-NOAA** [comment]
@MariaAristizabal-NOAA, @hyunsookkim-NOAA, and @BijuThomas-NOAA, please help to review the PR. This change is needed for HAFSv1 code freeze. Thanks!

**Comment by BijuThomas-NOAA** [comment]
> @MariaAristizabal-NOAA, @hyunsookkim-NOAA, and @BijuThomas-NOAA, please help to review the PR. This change is needed for HAFSv1 code freeze. Thanks!

@BinLiu-NOAA The changes look good to  me for adding debug option for HyCOM

**Review by BinLiu-NOAA — APPROVED** [review]
@BijuThomas-NOAA has tested and reviewed/approved these changes. 

Looks good to me as well.

**Comment by jkbk2004** [comment]
@BinLiu-NOAA https://github.com/ufs-community/ufs-weather-model/pull/1544 is ready. So, go ahead to merge in this pr, please.

**Comment by jkbk2004** [comment]
sorry merged already!

**Pull request merged**
